web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    # get "/", TopicController, :index
    # get "/topics/new", TopicController, :new
    # post "/topics", TopicController, :create
    # get "/topics/:id/edit", TopicController, :edit
    # put "/topics/:id", TopicController, :update
    # delete "/topics/:id", TopicController, :delete

    resources "/", TopicController
  end

  scope "/auth", Discuss do
    pipe_through :browser # Use the default browser stack
    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback

  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

lib/discuss/endpoint.ex
defmodule Discuss.Endpoint do
  use Phoenix.Endpoint, otp_app: :discuss

  socket "/socket", Discuss.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :discuss, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_discuss_key",
    signing_salt: "K98HJdt1"

  plug Discuss.Router
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss
end

web/models/comment.ex
defmodule Discuss.Comment do
  use Discuss.Web, :model

  schema "comments" do
     field :content, :string
     belongs_to :user, Discuss.User
     belongs_to :topic, Discuss.Topic

     timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params,[:content])
    |> validate_required([:content])
  end
end

web/models/topic.ex
defmodule Discuss.Topic do
  use Discuss.Web, :model

  schema "topics" do
    field :title, :string
    belongs_to :user, Discuss.Topic
    has_many :comments, Discuss.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params,[:title])
    |> validate_required([:title])
  end
end

web/models/user.ex
defmodule Discuss.User do
  use Discuss.Web, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment
    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params,[:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end

end

web/controllers/auth_controller.ex
defmodule Discuss.AuthController do
  use Discuss.Web, :controller

  plug Ueberauth
  alias Discuss.User

  def callback(%{assigns: %{ueberauth_auth: auth}} = conn,%{"provider" => provider} = params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: provider}
    changeset = User.changeset(%User{}, user_params)
    signin(conn, changeset)
  end

  defp signin(conn, changeset) do
    case insert_or_update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome Back")
        |> put_session(:user_id, user.id)
        |> redirect(to: topic_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:error, "Error Signing In")
        |> redirect(to: topic_path(conn, :index))
    end
  end
  defp insert_or_update(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
       nil ->
          Repo.insert(changeset)
       user -> {:ok, user}
    end
  end

  def logout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> put_flash(:info, "Successfully Signed Out")
    |> redirect(to: topic_path(conn, :index))
  end
end

web/controllers/topic_controller.ex
defmodule Discuss.TopicController do
  use Discuss.Web, :controller

  alias Discuss.Topic

  plug Discuss.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:edit, :update, :delete]

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})
    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic}) do
    changeset = conn.assigns.user
      |> build_assoc(:topics)
      |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Topic Created")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        render conn, "new.html", changeset: changeset
    end
  end

  def index(conn, _params) do
     topics = Repo.all(Topic)
     render conn, "index.html", topics: topics
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def edit(conn, %{"id" => topic_id}) do
     topic = Repo.get(Topic,topic_id)
     changeset = Topic.changeset(topic)
     render conn, "edit.html", changeset: changeset, topic: topic
  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    topic_old = Repo.get(Topic,topic_id)
    changeset = Topic.changeset(topic_old, topic)
    # changeset = Repo.get(Topic,topic_id) |> Topic.changeset(topic)
    case Repo.update(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Topic Updated")
        |> redirect(to: topic_path(conn, :index))
      {:error, changeset} ->
        render conn, "edit.html", changeset: changeset, topic: topic_old
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    # case Repo.delete(Repo.get(Topic,topic_id)) do
    #   {:ok, _post} ->
    #     conn
    #     |> put_flash(:info, "Topic Updated")
    #     |> redirect(to: topic_path(conn, :index))
    #   {:error, _changeset} ->
    #     conn
    #     |> put_flash(:error, "Topic Updated")
    #     |> redirect(to: topic_path(conn, :index))
    # end

    changeset = Repo.get!(Topic,topic_id) |> Repo.delete!

    conn
    |> put_flash(:info, "Topic Deleted")
    |> redirect(to: topic_path(conn, :index))
  end

  def check_topic_owner(conn, _params) do
     %{params:  %{"id" => topic_id}} = conn
     if Repo.get!(Topic, topic_id).user_id == conn.assigns.user.id do
       conn
     else
       conn
       |> put_flash(:error, "You cannot edit that")
       |> redirect(to: topic_path(conn, :index))
       |> halt()
     end

  end


end

web/views/error_view.ex
defmodule Discuss.ErrorView do
  use Discuss.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

web/views/topic_view.ex
defmodule Discuss.TopicView do
  use Discuss.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <nav class="light_blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo left">Discussions</a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <%= link "Logout", to: auth_path(@conn, :logout) %>
          <% else %>
            <li>
              <%= link "Sign In With Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Edit Topic", class: "btn btn-primary" %>
<% end %>

web/templates/topic/index.html.eex
<h5>Topics</h5>

<ul class="collection">
  <%= for topic <- @topics do %>
    <li class="collection-item">
      <!-- <%= topic.title %> -->
      <%= link topic.title, to: topic_path(@conn, :show, topic) %>
      <%= if @conn.assigns.user.id == topic.user_id do %>
      <div class="right">
        <%= link "Edit",  to: topic_path(@conn, :edit, topic) %>
        <%= link "Delete",  to: topic_path(@conn, :delete, topic), method: :delete %>
      </div>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</a>
</div>

web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

web/templates/topic/show.html.eex
<%= @topic.title %>